### ISSUE TITLE
Error: authentication required. Run 'reco auth' to authenticate

### ISSUE THREAD

**Issue by mhsamiei** [ReconfigureIO/reco#7]
when run reco build 
show this error in linux

**Comment by CampGareth** [comment]
Heya, it looks like you're trying to use reco without authenticating. You can get your API key from https://app.reconfigure.io/dashboard

If that doesn't work it might be because authentication is per-directory by default so while switching directories (for instance to change projects) you will have to re-authenticate.

If you're still having problems let us know 😄
